language: go
go:
 - 1.x
 - tip

go_import_path: stash.appscode.dev/cli

env:
  global:
  - GOFLAGS=-mod=vendor
  - GO111MODULE=on

cache:
  directories:
  - $HOME/.cache/go-build
  - $GOPATH/pkg/mod

install: true

script:
  - make lint
  - make
