apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: stash
spec:
  version: {VERSION}
  homepage: https://stash.run
  shortDescription: kubectl plugin for Stash by AppsCode
  description: |
    This plugin provides a list of commands to interact with Stash custom resources.
  platforms:
    - selector:
        matchLabels:
          os: darwin
          arch: amd64
      uri: https://github.com/stashed/cli/releases/download/{VERSION}/kubectl-stash-darwin-amd64.tar.gz
      sha256: {SHA256SUM_DARWIN_AMD64}
      files:
        - from: "*"
          to: "."
      bin: kubectl-stash-darwin-amd64
    - selector:
        matchLabels:
          os: darwin
          arch: arm64
      uri: https://github.com/stashed/cli/releases/download/{VERSION}/kubectl-stash-darwin-arm64.tar.gz
      sha256: {SHA256SUM_DARWIN_ARM64}
      files:
        - from: "*"
          to: "."
      bin: kubectl-stash-darwin-arm64
    - selector:
        matchLabels:
          os: linux
          arch: amd64
      uri: https://github.com/stashed/cli/releases/download/{VERSION}/kubectl-stash-linux-amd64.tar.gz
      sha256: {SHA256SUM_LINUX_AMD64}
      files:
        - from: "*"
          to: "."
      bin: kubectl-stash-linux-amd64
    - selector:
        matchLabels:
          os: linux
          arch: arm
      uri: https://github.com/stashed/cli/releases/download/{VERSION}/kubectl-stash-linux-arm.tar.gz
      sha256: {SHA256SUM_LINUX_ARM}
      files:
        - from: "*"
          to: "."
      bin: kubectl-stash-linux-arm
    - selector:
        matchLabels:
          os: linux
          arch: arm64
      uri: https://github.com/stashed/cli/releases/download/{VERSION}/kubectl-stash-linux-arm64.tar.gz
      sha256: {SHA256SUM_LINUX_ARM64}
      files:
        - from: "*"
          to: "."
      bin: kubectl-stash-linux-arm64
    - selector:
        matchLabels:
          os: windows
          arch: amd64
      uri: https://github.com/stashed/cli/releases/download/{VERSION}/kubectl-stash-windows-amd64.zip
      sha256: {SHA256SUM_WINDOWS_AMD64}
      files:
        - from: "*"
          to: "."
      bin: kubectl-stash-windows-amd64.exe
